name: "Bug Report"
description: "Report a bug or issue"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report Template
        
        Help us fix bugs quickly with detailed information.

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "Clear description of the bug"
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Step-by-step instructions to reproduce the bug"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What should happen instead?"
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Information about your environment"
      placeholder: |
        - OS: [e.g. iOS 15, Android 12, Windows 11]
        - App Version: [e.g. 1.0.0]
        - Device: [e.g. iPhone 13, Pixel 6, Desktop]
        - Flutter Version: [if known]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs/Screenshots"
      description: "Add logs, error messages, or screenshots"
      placeholder: "Paste logs or drag and drop screenshots here..."

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "Critical - App crashes or unusable"
        - "High - Major feature broken"
        - "Medium - Minor feature issue"
        - "Low - Cosmetic or enhancement"
    validations:
      required: true